### ISSUE TITLE
$input_purpose variable set but unused.

### ISSUE THREAD

**Issue by markdorison** [Lullabot/drupal_checksheet#3]
$input_purpose variable is set, but unused.

https://github.com/Lullabot/drupal_checksheet/blob/master/checksheet.module#L235

@justafish Should this line be removed or should we make use of it?

**Comment by justafish** [comment]
Yeah I have no idea what that was for :p

Removed, thanks! https://github.com/Lullabot/drupal_checksheet/commit/34b2f5785348329b80c4a605a99d9807ad7a0d21
